AWSTemplateFormatVersion: '2010-09-09'
Resources:
  StaticWebsiteS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: kishore-bucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${StaticWebsiteS3Bucket}/*'
            Principal: '*'
